### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by bkil** [yurt-page/docs#1]
Are you active on some forum or chat platform? Our aims seem to be very similar.

### alternatives.md

* https://github.com/bkil/freedom-fighters/blob/master/hu/server/palette-installer.md

### blog.md

What do you think about twtxt & yarn.social?

* https://twtxt.readthedocs.io/en/latest/user/twtxtfile.html
* https://yarn.social/about.html

### email.md

* https://web.archive.org/web/20220430135958/rawsontetley.org/proj_inetdxtra.html#smtp

### hosting.md

Actually you can use much more space within a browser nowadays through IndexedDB.

* https://en.wikipedia.org/wiki/Indexed_Database_API
* https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Browser_storage_limits_and_eviction_criteria#storage_limits

### webservers.md

* https://web.archive.org/web/20220430135958/rawsontetley.org/proj_inetdxtra.html#www
* https://github.com/dtaht/ceropackages-3.10/blob/master/net/inetdxtra/patches/001-strip.patch

**Comment by stokito** [comment]
Hi @bkil and thanks for your interest.
I checked few links that you provided and found them useful.
The main goal of this project is not to make a privacy oriented product.
Instead I want to make something very cheap, easy to use and popular (!).
Ideally something that you can have already pre-installed on your router or computer.

That means that I going to implement a central server on which users may authorize themselves.
This is a disaster in terms of privacy but makes life easier for average user.
That also means that you can install any tracking scripts like Google Ads.
And conform with local laws as much as possible.

**Comment by bkil** [comment]
I think we are still on the same page. And who is your team? Where do you conduct your planning discussions, where is your kanban board?

**Comment by stokito** [comment]
I don't want to ruin your expectations but I don't have any planning right now. And no team. Just few my friends who watching for the project. Only one guy really contributed and helped a lot but he is busy now.

I made public all Kanban boards. They are just cards with ideas and research results:
https://github.com/orgs/yurt-page/projects?type=classic

**Comment by stokito** [comment]
https://matrix.to/#/#yurtpage:matrix.org
